#1、获取token
POST http://localhost:8080/oauth/token?username=test&password=123456&grant_type=password&client_id=password_auth_mode&client_secret=123456
Content-Type: application/json
###
#2、带上access token就可以访问资源了
GET http://localhost:8081/user/zhangsan
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2UxIl0sImV4cCI6MTYyNDk4NzYxMSwidXNlcl9uYW1lIjoidGVzdCIsImp0aSI6IjAxNzdjYzRiLTBjY2MtNGI5OS1iMDlmLTIzZDYzZGQ2NTMwNiIsImNsaWVudF9pZCI6InBhc3N3b3JkX2F1dGhfbW9kZSIsInNjb3BlIjpbInJlYWRfdXNlcl9pbmZvIl19.q64YqHPwdUA41X1qr4iev1V1nN3MWT578i3LqgWNVZ47B1DsaflgFE525aiX1c5Rasqbyje4z1cxjrQm8NspfdHrSEEWK_4SiNU-Bj4-Kl558PdSNwZ1FAgqgLT_0uhDj-4eHIs8XdSCuDUeCVseg6N7Y5C0oUz_qbQfVnUqXuBFavJhFF3iGNza75MzK3PuFcYVWsmH1ZVHo78OuAkzmmuUJkzk4GvlrqVWTAysmHx5n-pcb_VFXkKTAO88cdl07gwT3bXv7Zh306i0Xz_0LhPECRD1s9zA_f0ZhFZBJmUUGeZcAwkFO5mb-IR_5BR793zVYQfv6WZHl7H_fnib5A
###
